#!/usr/bin/env node
/**
 * Single source of truth for the theme version: the root package.json.
 *
 * Runs automatically from the npm `version` lifecycle hook
 * (`npm version patch|minor|major`), and copies the version into:
 *   - src/theme/devfolio-theme/theme.json        → shown in HubSpot's theme settings
 *   - src/theme/devfolio-theme/package.json      → keeps the JS package in step
 *   - src/theme/devfolio-theme/components/shared/version.ts → rendered in the footer
 *
 * Usage: node scripts/sync-version.mjs [--check]
 *   --check  exit 1 if any file is out of sync (useful in CI / pre-deploy)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const themeDir = path.join(root, 'src/theme/devfolio-theme');
const checkOnly = process.argv.includes('--check');

const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));
const { version } = readJson(path.join(root, 'package.json'));
if (!/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(version)) {
  console.error(`✖ Invalid version in package.json: "${version}"`);
  process.exit(1);
}

const targets = [
  {
    file: path.join(themeDir, 'theme.json'),
    render: (current) => JSON.stringify({ ...readJson(current), version }, null, 2) + '\n',
  },
  {
    file: path.join(themeDir, 'package.json'),
    render: (current) => JSON.stringify({ ...readJson(current), version }, null, 2) + '\n',
  },
  {
    file: path.join(themeDir, 'components/shared/version.ts'),
    render: () =>
      `// Generated by scripts/sync-version.mjs. Do not edit by hand.\n` +
      `export const THEME_VERSION = '${version}';\n`,
  },
];

let outOfSync = 0;
for (const { file, render } of targets) {
  let current = '';
  try {
    current = readFileSync(file, 'utf8');
  } catch {
    /* file will be created */
  }
  const next = render(file);
  const rel = path.relative(root, file);
  if (current === next) {
    console.log(`  ✓ ${rel}`);
    continue;
  }
  outOfSync++;
  if (checkOnly) {
    console.log(`  ✖ ${rel} is out of sync`);
  } else {
    writeFileSync(file, next);
    console.log(`  ↻ ${rel} → ${version}`);
  }
}

if (checkOnly && outOfSync) {
  console.error(`\n✖ ${outOfSync} file(s) not at v${version}. Run: npm run version:sync`);
  process.exit(1);
}
console.log(`\nDevfolio v${version}`);
